[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "2.1.0"

[[constraint]]
  name = "github.com/cihub/seelog"
  version = "2.6.0"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/tomb.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
